version: "3"
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ../:/var/www/html
      - ./config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app-network
  db:
    image: mysql:5.7.34
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'the_spacebar'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
  client:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - app-network
volumes:
  db:
  www:
  nginx:

networks:
  app-network:
    driver: bridge